name: Update IP Databases

on:
  schedule:
    # 北京时间每天 08:00 (UTC 00:00) 运行
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-db:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare Output Directory
        run: mkdir -p output

      # ----------------------------------------------------------------
      # 1. IPinfo (Direct Download)
      # ----------------------------------------------------------------
      - name: Download IPinfo
        run: |
          echo "Downloading IPinfo..."
          curl -s -L -o output/ipinfo_lite.mmdb "https://ipinfo.io/data/ipinfo_lite.mmdb?_src=frontend&token=${{ secrets.IPINFO_TOKEN }}"
          echo "IPinfo downloaded."

      # ----------------------------------------------------------------
      # 2. DB-IP (Smart Date Fallback)
      # 逻辑：先尝试下载当月版本，如果 404（还没发布），则下载上个月版本
      # ----------------------------------------------------------------
      - name: Download DB-IP
        run: |
          # 获取当前月份 (e.g., 2026-02) 和上个月份 (e.g., 2026-01)
          CURRENT_MONTH=$(date +%Y-%m)
          PREV_MONTH=$(date -d "last month" +%Y-%m)
          
          declare -a types=("asn" "city" "country")
          
          for type in "${types[@]}"; do
            FILENAME="dbip-${type}-lite"
            URL_CURRENT="https://download.db-ip.com/free/${FILENAME}-${CURRENT_MONTH}.mmdb.gz"
            URL_PREV="https://download.db-ip.com/free/${FILENAME}-${PREV_MONTH}.mmdb.gz"
            
            echo "Attempting to download DB-IP $type for $CURRENT_MONTH..."
            
            # 尝试下载当月
            if curl --output /dev/null --silent --head --fail "$URL_CURRENT"; then
              wget -O "output/${FILENAME}.mmdb.gz" "$URL_CURRENT"
              echo "Downloaded $CURRENT_MONTH version."
            else
              echo "Current month ($CURRENT_MONTH) not found, trying previous month ($PREV_MONTH)..."
              wget -O "output/${FILENAME}.mmdb.gz" "$URL_PREV"
              echo "Downloaded $PREV_MONTH version."
            fi

            # 解压
            if [ -f "output/${FILENAME}.mmdb.gz" ]; then
              gunzip -f "output/${FILENAME}.mmdb.gz"
            fi
          done

      # ----------------------------------------------------------------
      # 3. MaxMind GeoLite2 (Updated Secret Name)
      # ----------------------------------------------------------------
      - name: Download MaxMind
        run: |
          declare -a editions=("GeoLite2-ASN" "GeoLite2-City" "GeoLite2-Country")
          
          for edition in "${editions[@]}"; do
            echo "Processing MaxMind $edition..."
            
            # 使用新变量名 MAXMIND_TOKEN
            URL="https://download.maxmind.com/app/geoip_download?edition_id=${edition}&license_key=${{ secrets.MAXMIND_TOKEN }}&suffix=tar.gz"
            
            wget -O "${edition}.tar.gz" "$URL"
            
            # 解压并提取 .mmdb
            mkdir -p temp_extract
            tar -xzf "${edition}.tar.gz" -C temp_extract
            find temp_extract -name "*.mmdb" -exec mv {} output/ \;
            
            # 清理
            rm "${edition}.tar.gz"
            rm -rf temp_extract
          done

      # ----------------------------------------------------------------
      # 4. IP2Location
      # ----------------------------------------------------------------
      - name: Download IP2Location
        run: |
          # 默认下载 DB11.LITE.BIN (IPv4/IPv6 City)
          CODE="DB11.LITE.BIN"
          
          echo "Downloading IP2Location $CODE..."
          wget -O "ip2location.zip" "https://www.ip2location.com/download/?token=${{ secrets.IP2LOCATION_TOKEN }}&file=$CODE"
          
          unzip -o ip2location.zip -d output/
          rm ip2location.zip

      # ----------------------------------------------------------------
      # 5. 删除旧 Release (保留最近 30 个)
      # 防止仓库爆满
      # ----------------------------------------------------------------
      - name: Delete Older Releases
        uses: dev-drprasad/delete-older-releases@v0.3.2
        with:
          keep_latest: 30
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # ----------------------------------------------------------------
      # 6. 发布新 Release
      # ----------------------------------------------------------------
      - name: Generate Release Tag
        id: tag
        run: echo "release_tag=$(date +'%Y.%m.%d')" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          name: IP Database Update ${{ steps.tag.outputs.release_tag }}
          files: output/*
          body: |
            Automatic daily update.
            Sources: IPinfo, DB-IP, MaxMind, IP2Location.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
